name: Build and Deploy Simple Java Maven App

# on:
#  push:
#    branches: [ "master" ] 
#  pull_request:
#    branches: [ "master" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('simple-java-maven-app/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy to Remote Server
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        scp: simple-java-maven-app/target/*.jar => /tmp/
        # Optional: Add commands to execute before or after SCP
        # first_ssh: |
        #   echo "Starting deployment..."
        # last_ssh: |
        #   echo "Deployment complete."
        #   # Example: Restart a service
        #   # ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart my-app.service"
